[package]
name = "secrets-manager"
version = "0.1.0"
edition = "2021"

[features]
mocks = ["dep:mockall"]

[dependencies]
async-trait = { version = "0.1.68" }
tracing = { version = "0.1.37" }
aws-config = { version = "0.54.1" }
aws-sdk-secretsmanager = { version = "0.24.0" }
serde_json = { version = "1.0.91" }
thiserror = { version = "1.0.40" }

# Used only with feature mock
mockall = { version = "0.11.4", optional = true }

[dev-dependencies]
mockall = { version = "0.11.4" }
tokio = { version = "1.27.0", features = ["macros"] }
