[package]
name = "secrets-manager"
version = "0.1.0"
edition = "2021"

[features]
mocks = ["dep:mockall"]

[dependencies]
async-trait = { version = "0.1.64" }
tracing = { version = "0.1.37" }
aws-config = { version = "0.51.0" }
aws-sdk-secretsmanager = { version = "0.21.0" }
serde_json = { version = "1.0.91" }
thiserror = { version = "1.0.38" }

# Used only with feature mock
mockall = { version = "0.11.3", optional = true }

[dev-dependencies]
mockall = { version = "0.11.3" }
tokio = { version = "1.25.0", features = ["macros"] }
