[workspace]

members = [
    "amqp",
    "env",
    "health_readiness",
    "httpw",
    "logging",
    "metrics",
    "migrator",
    "mqtt",
    "secrets_manager",
    "sql_pool",
    "traces",
    "auth",
]