[workspace]

members = [
    "events",
    "errors",
    "env",
    "logging",
    "mqtt",
    "amqp",
    "postgres",
    "traces",
    "metrics",
    "httpw",
    "health_readiness"
]

default-members  = [
    "events", 
    "errors", 
    "env", 
    "logging", 
    "mqtt", 
    "amqp", 
    "postgres",
    "traces",
    "metrics",
    "httpw",
]
